import { Building2, Contact, DollarSign, History } from "lucide-react";
import { CrmForms } from "@/components/CrmForms";
import { EmptyState } from "@/components/EmptyState";
import { MetricCard } from "@/components/MetricCard";
import { StatusBadge } from "@/components/StatusBadge";
import { getCrmSnapshot } from "@/lib/clawbot-service";

export const dynamic = "force-dynamic";

function money(value: number, currency: string) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(value);
}

export default async function CrmPage() {
  const { accounts, contacts, deals, activities } = await getCrmSnapshot();
  const accountById = new Map(accounts.map((account) => [account.id, account]));
  const openPipeline = deals.filter((deal) => !["won", "lost"].includes(deal.stage)).reduce((sum, deal) => sum + deal.value, 0);

  return (
    <div className="p-6 space-y-6 max-w-7xl">
      <div>
        <h1 className="text-xl font-semibold text-slate-100">CRM</h1>
        <p className="mt-0.5 text-sm text-slate-400">Accounts, contacts, pipeline, and activity generated by leads, operators, and agents.</p>
      </div>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <MetricCard title="Accounts" value={accounts.length} icon={Building2} />
        <MetricCard title="Contacts" value={contacts.length} icon={Contact} />
        <MetricCard title="Open Pipeline" value={money(openPipeline, "USD")} icon={DollarSign} />
        <MetricCard title="Activities" value={activities.length} icon={History} />
      </div>

      <CrmForms accounts={accounts} contacts={contacts} deals={deals} />

      <div className="grid grid-cols-1 gap-4 xl:grid-cols-2">
        <div className="rounded-xl border border-slate-800 bg-slate-900 overflow-hidden">
          <div className="grid grid-cols-4 gap-4 px-5 py-3 border-b border-slate-800 text-xs font-medium text-slate-500 uppercase tracking-wide">
            <span>Account</span><span>Owner</span><span>Status</span><span>Notes</span>
          </div>
          <div className="divide-y divide-slate-800/60">
            {accounts.length === 0 ? <EmptyState icon={Building2} title="No CRM accounts" description="Lead intake and manual CRM entry will populate accounts here." /> : accounts.map((account) => (
              <div key={account.id} className="grid grid-cols-4 gap-4 px-5 py-3 items-start hover:bg-slate-800/30 transition-colors">
                <div>
                  <p className="text-sm font-medium text-slate-200">{account.name}</p>
                  <p className="text-xs text-slate-500">{account.website || account.id}</p>
                </div>
                <span className="text-xs text-slate-400">{account.owner}</span>
                <StatusBadge status={account.status} />
                <p className="line-clamp-2 text-xs text-slate-500">{account.notes || account.industry || "-"}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="rounded-xl border border-slate-800 bg-slate-900 overflow-hidden">
          <div className="grid grid-cols-4 gap-4 px-5 py-3 border-b border-slate-800 text-xs font-medium text-slate-500 uppercase tracking-wide">
            <span>Deal</span><span>Account</span><span>Value</span><span>Stage</span>
          </div>
          <div className="divide-y divide-slate-800/60">
            {deals.length === 0 ? <EmptyState icon={DollarSign} title="No deals" description="Create a deal or let lead intake create a starter opportunity." /> : deals.map((deal) => (
              <div key={deal.id} className="grid grid-cols-4 gap-4 px-5 py-3 items-center hover:bg-slate-800/30 transition-colors">
                <div>
                  <p className="text-sm font-medium text-slate-200">{deal.name}</p>
                  <p className="text-xs text-slate-500">{deal.probability}% probability</p>
                </div>
                <span className="text-xs text-slate-400">{accountById.get(deal.accountId)?.name || deal.accountId}</span>
                <span className="text-xs text-slate-300">{money(deal.value, deal.currency)}</span>
                <StatusBadge status={deal.stage} />
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4 xl:grid-cols-2">
        <div className="rounded-xl border border-slate-800 bg-slate-900 overflow-hidden">
          <div className="grid grid-cols-4 gap-4 px-5 py-3 border-b border-slate-800 text-xs font-medium text-slate-500 uppercase tracking-wide">
            <span>Contact</span><span>Account</span><span>Title</span><span>Status</span>
          </div>
          <div className="divide-y divide-slate-800/60">
            {contacts.length === 0 ? <EmptyState icon={Contact} title="No contacts" description="Create contacts manually or capture them through lead intake." /> : contacts.map((contact) => (
              <div key={contact.id} className="grid grid-cols-4 gap-4 px-5 py-3 items-center hover:bg-slate-800/30 transition-colors">
                <div>
                  <p className="text-sm font-medium text-slate-200">{contact.name}</p>
                  <p className="text-xs text-slate-500">{contact.email || contact.id}</p>
                </div>
                <span className="text-xs text-slate-400">{contact.accountId ? accountById.get(contact.accountId)?.name || contact.accountId : "-"}</span>
                <span className="text-xs text-slate-400">{contact.title || "-"}</span>
                <StatusBadge status={contact.status} />
              </div>
            ))}
          </div>
        </div>

        <div className="rounded-xl border border-slate-800 bg-slate-900 overflow-hidden">
          <div className="grid grid-cols-4 gap-4 px-5 py-3 border-b border-slate-800 text-xs font-medium text-slate-500 uppercase tracking-wide">
            <span>Activity</span><span>Type</span><span>Status</span><span>When</span>
          </div>
          <div className="divide-y divide-slate-800/60">
            {activities.length === 0 ? <EmptyState icon={History} title="No activity" description="CRM changes, calls, emails, and notes will appear here." /> : activities.slice(0, 20).map((activity) => (
              <div key={activity.id} className="grid grid-cols-4 gap-4 px-5 py-3 items-center hover:bg-slate-800/30 transition-colors">
                <div>
                  <p className="text-sm font-medium text-slate-200">{activity.title}</p>
                  <p className="line-clamp-1 text-xs text-slate-500">{activity.body || activity.id}</p>
                </div>
                <span className="text-xs text-slate-400 capitalize">{activity.type.replace(/_/g, " ")}</span>
                <StatusBadge status={activity.status} />
                <span className="text-xs text-slate-500">{new Date(activity.occurredAt).toLocaleString()}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
